### ISSUE TITLE
Test  testInteractWithNoConnectionFast fails some times

### ISSUE THREAD

**Issue by myroslavlisniak** [servicefabric/servicefabric#10]
Test  testInteractWithNoConnectionFast fails some times, looks like we have some race condition either in test code or in production code.
https://travis-ci.org/servicefabric/servicefabric/jobs/76518170 - Travis build with failed tests

**Comment by myroslavlisniak** [comment]
Also another test is unstable
Travis build - https://travis-ci.org/servicefabric/servicefabric/jobs/76833257

**Comment by antonkharenko** [comment]
Fixed at https://github.com/servicefabric/servicefabric/commit/85fd20df271a0a9b860e11ed07d875bc67b94be9

**Comment by antonkharenko** [comment]
Fixed only partially. Main reason that handshake running in event executor:
pipeline.addLast(transportSpi.getEventExecutor(), "handshakeHandler", new ConnectorHandshakeChannelHandler(transportSpi));
And other code in event loop... so making concurrent changes and may produce race condition based behaviour at ConnectorHandshakeChannelHandler on:

```
@Override
	public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) {
		TransportChannel transport = transportSpi.getTransportChannel(ctx.channel());
		if (transport.shouldEnqueueSend()) {
			try {
				sendMailbox.put(new WriteAndFlush(msg, promise));
			} catch (InterruptedException e) {
				interrupted();
				if (promise != null)
					promise.setFailure(e);
				propagate(e);
			}
		} else {
			ctx.writeAndFlush(msg, promise);
		}
	}
```

**Comment by antonkharenko** [comment]
(continued)
It conflicts with the following code at TransportChannel:

```
public void send(@CheckForNull Message message, @Nullable SettableFuture<Void> promise) {
		checkArgument(message != null);
		if (shouldFailSend()) {
			if (promise != null)
				promise.setException(cause.get());
		} else {
			setPromise(channel.writeAndFlush(message), promise);
		}
	}
```

1. It passes shouldFailSend and go to writeAndFlush since state wasn't changed to Connect Failed
2. It reaches write method on handshake handler, but till that state was concurrently changed to connect failed and as result condition transport.shouldEnqueueSend() = false and go to ctx.writeAndFlush(...) branch where fails with channel closed exception.

**Comment by artem-v** [comment]
Already fixed. Closing it.
