### ISSUE TITLE
Define formatting settings

### ISSUE THREAD

**Issue by myroslavlisniak** [servicefabric/servicefabric#16]
Need to agreed about formatter settings and do next steps:
* define default formatting settings
* add configuration of formatter to repository,
* add checkstyle plugin to build process

**Comment by myroslavlisniak** [comment]
Guys let's use as default setting google java style:
[Google Java style] (http://google.github.io/styleguide/javaguide.html)
Also there is available formatter settings for eclipse and idea
[Formatter settings] (https://github.com/google/styleguide)
and checkstyle configuration:
[Checkstyle configuration](http://checkstyle.sourceforge.net/google_style.html)

What do you think?

**Comment by kshchepanovskyi** [comment]
Good idea.

**Comment by antonkharenko** [comment]
+1

**Comment by myroslavlisniak** [comment]
I propose to do next modification to the google style:
* Increase Line length from 100 to 140
* Change import order, package "com.google" should not be first, instead "io.servicefabric" should.

**Comment by antonkharenko** [comment]
Regards package order - it's ok. Line length 140 seems a lot.

**Comment by myroslavlisniak** [comment]
Ok, 120 than, but now we have lines that exceed this number

**Comment by myroslavlisniak** [comment]
Please review pull request: https://github.com/servicefabric/servicefabric/pull/35

**Comment by antonkharenko** [comment]
Resolved

**Comment by antonkharenko** [comment]
Set join wrapped lines to false
