### ISSUE TITLE
TransportChannel not sensitive to connection appearance

### ISSUE THREAD

**Issue by artem-v** [servicefabric/servicefabric#27]
Get ```TransportChannel``` using ```Transport.to()``` to a server endpoint which doesn't exist. And save a reference. Send messages in a loop using saved reference and check settable_futures. After some time start remote server endpoint. Now you will see settable_futures continue failing despite remote endpoint is up. 

Like this: 
```java
transportChannel = transport.to(...)
for(;;) {
transportChannel.send(...)
}
```
The issue is -- owning a reference to a ``TransportChannel`` is dangerous; client should always do ```transport.to(...)``` and shouldn't keep references around.

**Comment by antonkharenko** [comment]
Fixed at https://github.com/servicefabric/servicefabric/pull/37
